[package]
name = "snowstorm_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.20.1"
serde = { version = "1.0.218", features = ["derive"] }
surrealdb = { version = "2.2.1" }
symphonia = "0.5.4"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
